import { sql } from "drizzle-orm";

import { isValidCountryCode } from "@/lib/config/countries";
import { db } from "@/lib/db";

const VALID_GRANULARITIES = new Set([
  "1digit",
  "2digit",
  "3digit",
  "4digit",
  "5digit",
]);

/** Beyond this the client over-zooms the deepest tile it already has. */
const MAX_ZOOM = 12;

/** Web Mercator circumference in metres — one tile at z0. */
const WORLD_METRES = 40_075_016.685_578_5;

/**
 * Tile extent by zoom. The whole country sits in four z5 tiles, where 4096
 * units of precision per tile is far more than a screen can show — measured on
 * the German 5-digit set, dropping to 512 at country view takes a z5 screenful
 * from 497KB to 185KB with no visible difference.
 */
function extentForZoom(z: number): number {
  if (z <= 5) {
    return 512;
  }
  if (z <= 7) {
    return 1024;
  }
  if (z <= 9) {
    return 2048;
  }
  return 4096;
}

/**
 * Vector tiles for the postal-code polygons.
 *
 * The whole-country GeoJSON/TopoJSON payload does not scale: it grows with
 * every country and every granularity, and is paid in full on first load even
 * though a screen only ever shows a fraction of it. Tiles are generated by
 * PostGIS (ST_AsMVT), so there is no separate tile server to run.
 */
export async function GET(
  request: Request,
  {
    params,
  }: { params: Promise<{ granularity: string; z: string; x: string; y: string }> }
) {
  const { granularity, z, x, y } = await params;
  const zoom = Number.parseInt(z, 10);
  const tileX = Number.parseInt(x, 10);
  const tileY = Number.parseInt(y, 10);

  if (!VALID_GRANULARITIES.has(granularity)) {
    return Response.json({ error: "Invalid granularity" }, { status: 400 });
  }
  if (
    !Number.isInteger(zoom) ||
    !Number.isInteger(tileX) ||
    !Number.isInteger(tileY) ||
    zoom < 0 ||
    zoom > MAX_ZOOM
  ) {
    return Response.json({ error: "Invalid tile coordinates" }, { status: 400 });
  }
  const max = 2 ** zoom;
  if (tileX < 0 || tileX >= max || tileY < 0 || tileY >= max) {
    return Response.json({ error: "Tile out of range" }, { status: 400 });
  }

  const countries = (
    new URL(request.url).searchParams.get("country") ?? "DE"
  )
    .split(",")
    .map((c) => c.trim().toUpperCase())
    .filter((c) => isValidCountryCode(c));
  if (countries.length === 0) {
    return Response.json({ error: "Invalid country" }, { status: 400 });
  }

  const extent = extentForZoom(zoom);
  // Side of the square substituted for an outline that collapses at this zoom,
  // in metres: one and a half tile units, so it survives quantization.
  const minSize = (WORLD_METRES / 2 ** zoom / extent) * 1.5;

  const { rows } = await db.execute<{ mvt: Buffer | Uint8Array | null }>(sql`
    WITH bounds AS (
      SELECT ST_TileEnvelope(${zoom}, ${tileX}, ${tileY}) AS env
    ),
    src AS (
      SELECT pc.code,
             pc.country,
             -- A small postal code is sub-unit at country zoom and quantizes
             -- away to nothing, which would make a city-only layer render as
             -- an empty map. Fall back to a marker square around the code's
             -- representative point so every code is always drawn.
             COALESCE(
               ST_AsMVTGeom(
                 ST_Transform(pc.geometry, 3857),
                 bounds.env,
                 ${extent},
                 8,
                 true
               ),
               ST_AsMVTGeom(
                 ST_Envelope(
                   ST_Buffer(
                     ST_Transform(ST_PointOnSurface(pc.geometry), 3857),
                     ${minSize}
                   )
                 ),
                 bounds.env,
                 ${extent},
                 8,
                 true
               )
             ) AS geom
      FROM postal_codes pc, bounds
      WHERE pc.country IN (${sql.join(
        countries.map((c) => sql`${c}`),
        sql`, `
      )})
        AND pc.granularity = ${granularity}
        AND pc.is_active = 'true'
        AND ST_Transform(pc.geometry, 3857) && bounds.env
    )
    SELECT ST_AsMVT(src, 'plz', ${extent}, 'geom') AS mvt
    FROM src
    WHERE src.geom IS NOT NULL
  `);

  const mvt = rows[0]?.mvt;
  const body = mvt ? new Uint8Array(mvt as Uint8Array) : new Uint8Array(0);

  // MVT is protobuf rather than entropy-coded, and gzip takes a z5 screenful of
  // these tiles from 899KB to 185KB — but Vercel neither compresses
  // application/vnd.mapbox-vector-tile itself nor forwards a body we compressed
  // under that type: it decompresses it at the edge and drops the header, which
  // put 257KB on the wire for a tile that was 101KB leaving the function. It
  // does forward gzip for application/octet-stream, and deck.gl picks the MVT
  // parser from the layer rather than from the response type (MVTLayer sets
  // loadOptions.core.mimeType itself), so the tiles go out as octet-stream.
  const stream = new Blob([body as BlobPart])
    .stream()
    .pipeThrough(new CompressionStream("gzip"));

  return new Response(stream, {
    status: 200,
    headers: {
      "Content-Type": "application/octet-stream",
      "Content-Encoding": "gzip",
      // Tiles change only when the postal-code dataset is reimported.
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
    },
  });
}
