import { sql } from "drizzle-orm";

import { type CountryCode, isValidCountryCode } from "@/lib/config/countries";
import { db } from "@/lib/db";

const VALID_GRANULARITIES = new Set([
  "1digit",
  "2digit",
  "3digit",
  "4digit",
  "5digit",
]);

/** Beyond this the client should already have the detail it needs. */
const MAX_ZOOM = 12;

/**
 * Tile extent by zoom. The whole country sits in four z5 tiles, where 4096
 * units of precision per tile is far more than a screen can show — measured on
 * the German 5-digit set, dropping to 512 at country view takes a z5 screenful
 * from 497KB to 181KB with no visible difference.
 */
function extentForZoom(z: number): number {
  if (z <= 5) {
    return 512;
  }
  if (z <= 7) {
    return 1024;
  }
  if (z <= 9) {
    return 2048;
  }
  return 4096;
}

/**
 * Vector tiles for the postal-code polygons.
 *
 * The whole-country GeoJSON/TopoJSON payload does not scale: it grows with
 * every country and every granularity, and is paid in full on first load even
 * though a screen only ever shows a fraction of it. Tiles are generated by
 * PostGIS (ST_AsMVT), so there is no separate tile server to run.
 */
export async function GET(
  request: Request,
  {
    params,
  }: { params: Promise<{ granularity: string; z: string; x: string; y: string }> }
) {
  const { granularity, z, x, y } = await params;
  const zoom = Number.parseInt(z, 10);
  const tileX = Number.parseInt(x, 10);
  const tileY = Number.parseInt(y, 10);

  if (!VALID_GRANULARITIES.has(granularity)) {
    return Response.json({ error: "Invalid granularity" }, { status: 400 });
  }
  if (
    !Number.isInteger(zoom) ||
    !Number.isInteger(tileX) ||
    !Number.isInteger(tileY) ||
    zoom < 0 ||
    zoom > MAX_ZOOM
  ) {
    return Response.json({ error: "Invalid tile coordinates" }, { status: 400 });
  }
  const max = 2 ** zoom;
  if (tileX < 0 || tileX >= max || tileY < 0 || tileY >= max) {
    return Response.json({ error: "Tile out of range" }, { status: 400 });
  }

  const countryParam = new URL(request.url).searchParams.get("country");
  const country: CountryCode =
    countryParam && isValidCountryCode(countryParam) ? countryParam : "DE";
  const extent = extentForZoom(zoom);

  const { rows } = await db.execute<{ mvt: Buffer | Uint8Array | null }>(sql`
    WITH bounds AS (
      SELECT ST_TileEnvelope(${zoom}, ${tileX}, ${tileY}) AS env
    ),
    src AS (
      SELECT pc.code,
             ST_AsMVTGeom(
               ST_Transform(pc.geometry, 3857),
               bounds.env,
               ${extent},
               8,
               true
             ) AS geom
      FROM postal_codes pc, bounds
      WHERE pc.country = ${country}
        AND pc.granularity = ${granularity}
        AND pc.is_active = 'true'
        AND ST_Transform(pc.geometry, 3857) && bounds.env
    )
    SELECT ST_AsMVT(src, 'plz', ${extent}, 'geom') AS mvt
    FROM src
    WHERE src.geom IS NOT NULL
  `);

  const mvt = rows[0]?.mvt;
  const body = mvt ? new Uint8Array(mvt as Uint8Array) : new Uint8Array(0);

  return new Response(body as BodyInit, {
    status: 200,
    headers: {
      "Content-Type": "application/vnd.mapbox-vector-tile",
      // Tiles change only when the postal-code dataset is reimported.
      "Cache-Control": "public, max-age=86400, stale-while-revalidate=604800",
    },
  });
}
