"use server";

import { eq, and, inArray, sql } from "drizzle-orm";
import { updateTag } from "next/cache";

import { db } from "../../lib/db";
import {
  areaVersions,
  areas,
  areaLayers,
  areaLayerPostalCodes,
  areaChanges,
} from "../../lib/schema/schema";
import { clearUndoRedoStacksAction } from "./change-tracking-actions";

type ServerActionResponse<T = void> = Promise<{
  success: boolean;

  data?: T;

  error?: string;
}>;

interface VersionSnapshot {
  areaName: string;
  description: string | null;
  granularity: string;
  layers: {
    id: number;
    name: string;
    color: string;
    opacity: number;
    isVisible: string;
    orderIndex: number;
    postalCodes: string[];
  }[];
}

// ===============================

// VERSION CREATION

// ===============================

/**
 * Create a new version (snapshot) of the current area state
 */

export async function createVersionAction(
  areaId: number,

  data: {
    name?: string;

    description?: string;

    changesSummary?: string;

    createdBy?: string;

    branchName?: string;

    fromVersionId?: number; // If branching from a specific version
  }
): ServerActionResponse<{ areaId: number; versionNumber: number }> {
  try {
    const result = await db.transaction(async (tx) => {
      // Get current area with all layers and postal codes

      const area = await tx.query.areas.findFirst({
        where: eq(areas.id, areaId),

        with: {
          layers: {
            with: {
              postalCodes: true,
            },

            orderBy: (layers, { asc }) => [asc(layers.orderIndex)],
          },
        },
      });

      if (!area) {
        throw new Error("Area not found");
      }

      // Get change count since last version or from start

      const changeCount = await tx

        .select({ count: sql<number>`count(*)` })

        .from(areaChanges)

        .where(
          and(
            eq(areaChanges.areaId, areaId),

            data.fromVersionId
              ? eq(areaChanges.versionAreaId, data.fromVersionId)
              : eq(areaChanges.versionAreaId, sql`NULL`)
          )
        );

      // Create snapshot

      const snapshot = {
        areaName: area.name,

        description: area.description,

        granularity: area.granularity,

        layers: area.layers.map((layer) => ({
          id: layer.id,

          name: layer.name,

          color: layer.color,

          opacity: layer.opacity,

          isVisible: layer.isVisible,

          orderIndex: layer.orderIndex,

          postalCodes: layer.postalCodes?.map((pc) => pc.postalCode) || [],
        })),
      };

      // Deactivate all previous versions for this area

      await tx

        .update(areaVersions)

        .set({ isActive: "false" })

        .where(eq(areaVersions.areaId, areaId));

      // Create the version - versionNumber will be auto-generated by trigger

      const [version] = await tx

        .insert(areaVersions)

        .values({
          areaId,

          // versionNumber will be auto-generated by trigger - don't pass it

          name: data.name,

          description: data.description,

          snapshot,

          changesSummary: data.changesSummary,

          parentVersionAreaId: null, // Will be set when branching

          parentVersionNumber: null, // Will be set when branching

          branchName: data.branchName,

          isActive: "true",

          changeCount: changeCount[0]?.count || 0,

          createdBy: data.createdBy,
        })

        .returning();

      // Update area's current version

      await tx

        .update(areas)

        .set({ currentVersionNumber: version.versionNumber })

        .where(eq(areas.id, areaId));

      // Update all uncommitted changes to be associated with this version

      await tx

        .update(areaChanges)

        .set({
          versionAreaId: version.areaId,

          versionNumber: version.versionNumber,
        })

        .where(
          and(
            eq(areaChanges.areaId, areaId),

            eq(areaChanges.versionAreaId, sql`NULL`)
          )
        );

      return { areaId: version.areaId, versionNumber: version.versionNumber };
    });

    // Clear undo/redo stacks after creating version

    await clearUndoRedoStacksAction(areaId);

    updateTag("versions");
    updateTag(`area-${areaId}-versions`);
    updateTag(`area-${areaId}`);
    updateTag(`area-${areaId}-undo-redo`);
    updateTag("version-info");
    updateTag(`area-${areaId}-version-info`);

    return { success: true, data: result };
  } catch (error) {
    console.error("Error creating version:", error);

    return {
      success: false,

      error:
        error instanceof Error ? error.message : "Failed to create version",
    };
  }
}

// ===============================

// VERSION RESTORATION & BRANCHING

// ===============================

/**
 * Restore a version as the current working state (creates a new branch)
 */

export async function restoreVersionAction(
  areaId: number,

  versionNumber: number,

  options?: {
    createBranch?: boolean;

    branchName?: string;

    createdBy?: string;
  }
): ServerActionResponse<{ newVersionNumber?: number }> {
  try {
    const result = await db.transaction(async (tx) => {
      // Get the version to restore

      const version = await tx.query.areaVersions.findFirst({
        where: and(
          eq(areaVersions.areaId, areaId),

          eq(areaVersions.versionNumber, versionNumber)
        ),
      });

      if (!version) {
        throw new Error("Version not found");
      }

      const snapshot = version.snapshot as VersionSnapshot;

      // Delete all current layers

      const currentLayers = await tx

        .select({ id: areaLayers.id })

        .from(areaLayers)

        .where(eq(areaLayers.areaId, areaId));

      if (currentLayers.length > 0) {
        const layerIds = currentLayers.map((l) => l.id);

        // Use inArray instead of ANY for proper Drizzle syntax

        await tx

          .delete(areaLayerPostalCodes)

          .where(inArray(areaLayerPostalCodes.layerId, layerIds));

        await tx.delete(areaLayers).where(eq(areaLayers.areaId, areaId));
      }

      // Restore layers from snapshot — batch insert all layers at once,
      // then batch insert all postal codes together (avoids N sequential round-trips)
      if (snapshot.layers.length > 0) {
        const insertedLayers = await tx
          .insert(areaLayers)
          .values(
            snapshot.layers.map((layerData) => ({
              areaId,
              name: layerData.name,
              color: layerData.color,
              opacity: layerData.opacity,
              isVisible: layerData.isVisible,
              orderIndex: layerData.orderIndex,
            }))
          )
          .returning();

        // Collect all postal code rows from all layers
        const allPostalCodeRows = insertedLayers.flatMap((layer, i) =>
          (snapshot.layers[i].postalCodes ?? []).map((code: string) => ({
            layerId: layer.id,
            postalCode: code,
          }))
        );

        // Batch insert with chunks of 500 to stay within DB limits
        const BATCH_SIZE = 500;
        for (let i = 0; i < allPostalCodeRows.length; i += BATCH_SIZE) {
          await tx
            .insert(areaLayerPostalCodes)
            .values(allPostalCodeRows.slice(i, i + BATCH_SIZE));
        }
      }

      // Update area properties if they changed

      await tx

        .update(areas)

        .set({
          name: snapshot.areaName,

          description: snapshot.description,

          granularity: snapshot.granularity,
        })

        .where(eq(areas.id, areaId));

      // Create a new version if branching

      let newVersionId: number | undefined;

      if (options?.createBranch) {
        // versionNumber will be auto-generated by trigger

        const [newVersion] = await tx

          .insert(areaVersions)

          .values({
            areaId,

            // versionNumber will be auto-generated by trigger - don't pass it

            name: options.branchName || `Branch from v${version.versionNumber}`,

            description: `Restored from version ${version.versionNumber}`,

            snapshot: version.snapshot,

            parentVersionAreaId: version.areaId,

            parentVersionNumber: version.versionNumber,

            branchName: options.branchName,

            isActive: "true",

            changeCount: 0,

            createdBy: options.createdBy,
          })

          .returning();

        newVersionId = newVersion.versionNumber;

        // Update area's current version

        await tx

          .update(areas)

          .set({ currentVersionNumber: newVersion.versionNumber })

          .where(eq(areas.id, areaId));
      }

      return { newVersionNumber: newVersionId };
    });

    // Clear undo/redo stacks after restoration

    await clearUndoRedoStacksAction(areaId);

    updateTag("versions");
    updateTag(`area-${areaId}-versions`);
    updateTag(`area-${areaId}`);
    updateTag(`area-${areaId}-layers`);
    updateTag(`area-${areaId}-undo-redo`);
    updateTag("version-info");
    updateTag(`area-${areaId}-version-info`);

    return { success: true, data: result };
  } catch (error) {
    console.error("Error restoring version:", error);

    return {
      success: false,

      error:
        error instanceof Error ? error.message : "Failed to restore version",
    };
  }
}

/**
 * Compare two versions and get differences
 */

export async function compareVersionsAction(
  areaId1: number,

  versionNumber1: number,

  areaId2: number,

  versionNumber2: number
): ServerActionResponse<{
  layersAdded: VersionSnapshot["layers"];

  layersRemoved: VersionSnapshot["layers"];

  layersModified: VersionSnapshot["layers"];

  postalCodesAdded: string[];

  postalCodesRemoved: string[];
}> {
  try {
    const [version1, version2] = await Promise.all([
      db.query.areaVersions.findFirst({
        where: and(
          eq(areaVersions.areaId, areaId1),

          eq(areaVersions.versionNumber, versionNumber1)
        ),
      }),

      db.query.areaVersions.findFirst({
        where: and(
          eq(areaVersions.areaId, areaId2),

          eq(areaVersions.versionNumber, versionNumber2)
        ),
      }),
    ]);

    if (!version1 || !version2) {
      return { success: false, error: "One or both versions not found" };
    }

    const snapshot1 = version1.snapshot as VersionSnapshot;

    const snapshot2 = version2.snapshot as VersionSnapshot;

    // Compare layers

    const layers1Map = new Map(snapshot1.layers.map((l) => [l.name, l]));

    const layers2Map = new Map(snapshot2.layers.map((l) => [l.name, l]));

    const layersAdded = snapshot2.layers.filter((l) => !layers1Map.has(l.name));

    const layersRemoved = snapshot1.layers.filter(
      (l) => !layers2Map.has(l.name)
    );

    const layersModified = snapshot2.layers.filter((l2) => {
      const l1 = layers1Map.get(l2.name);

      if (!l1) {
        return false;
      }

      return (
        l1.color !== l2.color ||
        l1.opacity !== l2.opacity ||
        JSON.stringify(l1.postalCodes.sort()) !==
          JSON.stringify(l2.postalCodes.sort())
      );
    });

    // Compare postal codes

    const allCodes1 = new Set(snapshot1.layers.flatMap((l) => l.postalCodes));

    const allCodes2 = new Set(snapshot2.layers.flatMap((l) => l.postalCodes));

    const postalCodesAdded = [...allCodes2].filter((c) => !allCodes1.has(c));

    const postalCodesRemoved = [...allCodes1].filter((c) => !allCodes2.has(c));

    return {
      success: true,

      data: {
        layersAdded,

        layersRemoved,

        layersModified,

        postalCodesAdded,

        postalCodesRemoved,
      },
    };
  } catch (error) {
    console.error("Error comparing versions:", error);

    return { success: false, error: "Failed to compare versions" };
  }
}
